; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
; no reorg => recruitment 10-20 CBS and new manager alexandre maria temporary
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:unihiker_k10]
platform = unihiker
board = unihiker_k10
framework = arduino
monitor_speed = 115200
test_build_src = yes
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
board_upload.filesystem_partition = voice_data

build_unflags =
	-std=gnu++11
	-std=gnu++14
	-std=c++11
	-std=c++14

build_flags = 
	-std=gnu++17
	-DCORE_DEBUG_LEVEL=3
	-DLOG_LOCAL_LEVEL=ESP_LOG_WARN
	-DCONFIG_LOG_COLORS=0
	-DSERVO_VERBOSE_DEBUG=1
	; -DCONFIG_ESP32_SPIRAM_SUPPORT=y ; for https://github.com/espressif/esp32-camera
lib_deps = 
	Preferences@^2.0.0
	https://github.com/bblanchon/ArduinoJson.git	
	https://github.com/ESP32Async/ESPAsyncWebServer.git
	https://github.com/ESP32Async/AsyncTCP.git
	; johnosbb/MicroTFLite @ ^1.0.4 --- IGNORE ---
	; esp32-camera ;' for https://github.com/espressif/esp32-camera
